INSERT INTO catagories (name, description)
VALUES ('bakery', 'baked goods')
INSERT INTO catagories (name, description)
VALUES ('beverage', 'packaged beverages')
INSERT INTO catagories (name, description)
VALUES ('produce', 'vegetables and fresh herbs')
INSERT INTO catagories (name, description)
VALUES ('deli', 'processed deli meats')
INSERT INTO catagories (name, description)
VALUES ('processed', 'processed shelf stable goods')
INSERT INTO catagories (name, description)
VALUES ('meat', 'meat from butcher')
INSERT INTO catagories (name, description)
VALUES ('seafood', 'fish and shellfish')
INSERT INTO catagories (name, description)
VALUES ('dairy', 'cheese, milk and processed milk products')
INSERT INTO catagories (name, description)
VALUES ('other', 'uncategorised')
